spring.application.name=ai-agent-backend

langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.chat-model.base-url=${OPENAI_BASE_URL:https://api.openai.com/v1}
langchain4j.open-ai.chat-model.model-name=${OPENAI_MODEL:gpt-5.4}
